version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      # - mongo
      - postgres
    env_file:
      - .env

  # Uncomment the following to use postgres
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: personal-website
    ports:
      - '5432:5432'
    volumes:
      - personal-website-pgdata:/var/lib/postgresql/data

volumes:
  data:
  personal-website-pgdata:
  node_modules:
